bump google provider version to 5.12
PaloAltoNetworks/terraform-google-swfw-modules pull request #7
Opened 2024-01-17 17:48 UTC by MyMirelHub

## Description

## Motivation and Context

## How Has This Been Tested?

## Screenshots (if appropriate)

## Types of changes

- Bug fix (non-breaking change which fixes an issue)
- New feature (non-breaking change which adds functionality)
- Breaking change (fix or feature that would cause existing functionality to change)

## Checklist

- [ ] I have updated the documentation accordingly.
- [ ] I have read the **CONTRIBUTING** document.
- [ ] I have added tests to cover my changes if appropriate.
- [ ] All new and existing tests passed.

2024-02-08 11:38 UTC, michalbil commented
/validate paths="modules/autoscale modules/iam_service_account modules/lb_http_ext_global modules/panorama modules/vpc modules/vpn modules/bootstrap modules/lb_external modules/lb_internal modules/vmseries modules/vpc-peering"

2024-02-08 23:57 UTC, michalbil commented
/validate paths="modules/autoscale modules/iam_service_account modules/lb_http_ext_global modules/panorama modules/vpc modules/vpn modules/bootstrap modules/lb_external modules/lb_internal modules/vmseries modules/vpc-peering"

2024-02-09 12:37 UTC, michalbil commented
@MyMirelHub there is one issue with `google_secret_manager_secret` argument that needs to be fixed to work with the new provider version, details can be found in validation job logs.

2024-04-02 20:09 UTC, pavelrn commented
/validate paths="modules/autoscale modules/iam_service_account modules/lb_http_ext_global modules/panorama modules/vpc modules/vpn modules/bootstrap modules/lb_external modules/lb_internal modules/vmseries modules/vpc-peering"

2024-04-02 20:33 UTC, pavelrn commented
/validate paths="modules/autoscale modules/iam_service_account modules/lb_http_ext_global modules/panorama modules/vpc modules/vpn modules/bootstrap modules/lb_external modules/lb_internal modules/vmseries modules/vpc-peering"

2024-04-02 20:37 UTC, pavelrn approved these changes

2024-04-03 00:05 UTC, michalbil requested changes
@pavelrn can you please update PR title to reflect the changes?

2024-04-03 00:05 UTC, michalbil commented on modules/autoscale/versions.tf
> +      version = ">= 5.0.0"
```suggestion
      version = ">= 5"
```

2024-04-03 08:40 UTC, pavelrn commented on modules/autoscale/versions.tf
> +      version = ">= 5.0.0"
Sure!

2024-04-03 08:47 UTC, pavelrn approved these changes

2024-04-03 13:51 UTC, michalbil approved these changes

2024-04-03 13:55 UTC, merged